// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// METEOR_CPP
SEXP METEOR_CPP(SEXP Zscore_in, SEXP Sigma_in, SEXP N_in, SEXP p_in, SEXP k_in, SEXP Omega_in, SEXP Gibbsnumberin, SEXP burninproportion, SEXP pi_beta_shape_in, SEXP pi_beta_scale_in, SEXP pi_1_shape_in, SEXP pi_1_scale_in, SEXP pi_0_shape_in, SEXP pi_0_scale_in);
RcppExport SEXP _METEOR_METEOR_CPP(SEXP Zscore_inSEXP, SEXP Sigma_inSEXP, SEXP N_inSEXP, SEXP p_inSEXP, SEXP k_inSEXP, SEXP Omega_inSEXP, SEXP GibbsnumberinSEXP, SEXP burninproportionSEXP, SEXP pi_beta_shape_inSEXP, SEXP pi_beta_scale_inSEXP, SEXP pi_1_shape_inSEXP, SEXP pi_1_scale_inSEXP, SEXP pi_0_shape_inSEXP, SEXP pi_0_scale_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Zscore_in(Zscore_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sigma_in(Sigma_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type N_in(N_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p_in(p_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k_in(k_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Omega_in(Omega_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gibbsnumberin(GibbsnumberinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type burninproportion(burninproportionSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_shape_in(pi_beta_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_beta_scale_in(pi_beta_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_1_shape_in(pi_1_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_1_scale_in(pi_1_scale_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_0_shape_in(pi_0_shape_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pi_0_scale_in(pi_0_scale_inSEXP);
    rcpp_result_gen = Rcpp::wrap(METEOR_CPP(Zscore_in, Sigma_in, N_in, p_in, k_in, Omega_in, Gibbsnumberin, burninproportion, pi_beta_shape_in, pi_beta_scale_in, pi_1_shape_in, pi_1_scale_in, pi_0_shape_in, pi_0_scale_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_METEOR_METEOR_CPP", (DL_FUNC) &_METEOR_METEOR_CPP, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_METEOR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
