# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' METEOR
#' 
#' @export
METEOR_CPP <- function(Zscore_in, Sigma_in, N_in, p_in, k_in, Omega_in, Gibbsnumberin, burninproportion, pi_beta_shape_in, pi_beta_scale_in, pi_1_shape_in, pi_1_scale_in, pi_0_shape_in, pi_0_scale_in) {
    .Call(`_METEOR_METEOR_CPP`, Zscore_in, Sigma_in, N_in, p_in, k_in, Omega_in, Gibbsnumberin, burninproportion, pi_beta_shape_in, pi_beta_scale_in, pi_1_shape_in, pi_1_scale_in, pi_0_shape_in, pi_0_scale_in)
}

